export const HOSTS = {
  BASE_API_URL: "",

  userService: "/api/users",
  cvService: "/api/cvs",
  authService: "/api/auth",
  chatbotService: "/api/chatbot/",
  companyService: "/api/departments",
  jobService: "/api/jobs",
  reviewService: "/api/reviews",
  reportService: "/api/reports",
  applicationService: "/api/applications",
  cvAIService: "/api/cvai",
  matchingService: "/api/matching",
  emailService: "/api/email",
  walletService: "/api/wallet",
  paymentService: "/api/payment",
  interviewService: "/api/interviews",
  chatService: "/api/chat",
  notificationService: "/api/notifications",
  termService: "/api/terms",
  // socket: "http://47.129.8.162:7000",
  // chat_socket: "http://47.129.8.162:1000",
  socket: "http://52.76.22.144/socket.io",
  chat_socket: "http://52.76.22.144/chat.io",

};

// export const HOSTS = {
//   BASE_API_URL: "",

//   userService: "http://localhost:2222/api/users",
//   cvService: "http://localhost:2222/api/cvs",
//   authService: "http://localhost:1111/api/auth",
//   chatbotService: "http://localhost:3333/api/chatbot/",
//   companyService: "http://localhost:4444/api/departments",
//   jobService: "http://localhost:4444/api/jobs",
//   reviewService: "http://localhost:4444/api/reviews",
//   reportService: "http://localhost:4444/api/reports",
//   applicationService: "http://localhost:5555/api/applications",
//   cvAIService: "http://localhost:8080/api/cvai",
//   matchingService: "http://localhost:6789/api/matching",
//   emailService: "http://localhost:5000/api/email",
//   walletService: "http://localhost:7777/api/wallet",
//   paymentService: "http://localhost:7777/api/payment",
//   interviewService: "http://localhost:1000/api/interviews",
//   chatService: "http://localhost:1000/api/chat",
//   notificationService: "http://localhost:7000/api/notifications",
//   termService: "http://localhost:2222/api/terms",
//   // socket: "http://47.129.8.162:7000",
//   // chat_socket: "http://47.129.8.162:1000",
//   socket: "http://localhost:7000",
//   chat_socket: "http://localhost:1000",
// };
